version: '3'

services:
  fiji:
    image: gnasello/fiji-env
    build: .
    ports:
      - $GUIPORT:8080
    volumes:
      - $HOME_RESEARCHER:/data # change the path before ":" with the volume you want to mount
    hostname: $HOST_NAME
    container_name: fiji-app
    environment:
       - GUIPORT=${GUIPORT}
       - HOME_RESEARCHER=${HOME_RESEARCHER}
       - HOST_NAME=${HOST_NAME}