services:
  fiji-env:
    image: gnasello/fiji-env:2024-07-16
    container_name: fiji
    security_opt:
      - seccomp:unconfined # for terminal to work
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- SUBFOLDER=/ #optional
      - TITLE=Fiji #optional
    #volumes:
      #- /home/luna.kuleuven.be/u0128401:/config/researcher_home
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    #devices:
      #- /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional